### ISSUE TITLE
UI API called on a background thread: -[UIApplication canOpenURL:]

### ISSUE THREAD

**Issue by ghost** [Accengage/accengage-ios-sdk-releases#1]
I just wanted to let you aware of this warning coming from the Main Thread Checker:
**Main Thread Checker: UI API called on a background thread: -[UIApplication canOpenURL:]**

> =================================================================
> Main Thread Checker: UI API called on a background thread: -[UIApplication canOpenURL:]
> PID: 52436, TID: 1300976, Thread name: (none), Queue name: com.apple.usernotifications.UNUserNotificationServiceConnection.call-out, QoS: 0
> Backtrace:
> 4   Accengage                           0x00000001039db672 __22+[BMA4SLogger enabled]_block_invoke + 96
> 5   libdispatch.dylib                   0x0000000109625848 _dispatch_client_callout + 8
> 6   libdispatch.dylib                   0x0000000109626dc0 dispatch_once_f + 285
> 7   Accengage                           0x00000001039db610 +[BMA4SLogger enabled] + 101
> 8   Accengage                           0x00000001039dc8c8 _A4SLog + 84
> 9   Accengage                           0x00000001039dcc68 A4SLog + 521
> 10  Accengage                           0x00000001039eb99a -[ACCPush resetBadge] + 23
> 11  Accengage                           0x00000001039ee907 __61-[ACCPush updateAuthorizedNotificationOptionsWithBadgeReset:]_block_invoke + 240
> 12  libdispatch.dylib                   0x0000000109624807 _dispatch_call_block_and_release + 12
> 13  libdispatch.dylib                   0x0000000109625848 _dispatch_client_callout + 8
> 14  libdispatch.dylib                   0x000000010962dc41 _dispatch_queue_serial_drain + 1305
> 15  libdispatch.dylib                   0x000000010962e556 _dispatch_queue_invoke + 328
> 16  libdispatch.dylib                   0x000000010962a3a0 _dispatch_queue_override_invoke + 726
> 17  libdispatch.dylib                   0x00000001096313c8 _dispatch_root_queue_drain + 664
> 18  libdispatch.dylib                   0x00000001096310d2 _dispatch_worker_thread3 + 132
> 19  libsystem_pthread.dylib             0x0000000109beb169 _pthread_wqthread + 1387
> 20  libsystem_pthread.dylib             0x0000000109beabe9 start_wqthread + 13
> [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication canOpenURL:]
> PID: 52436, TID: 1300976, Thread name: (none), Queue name: com.apple.usernotifications.UNUserNotificationServiceConnection.call-out, QoS: 0
> Backtrace:
> 4   Accengage                           0x00000001039db672 __22+[BMA4SLogger enabled]_block_invoke + 96
> 5   libdispatch.dylib                   0x0000000109625848 _dispatch_client_callout + 8
> 6   libdispatch.dylib                   0x0000000109626dc0 dispatch_once_f + 285
> 7   Accengage                           0x00000001039db610 +[BMA4SLogger enabled] + 101
> 8   Accengage                           0x00000001039dc8c8 _A4SLog + 84
> 9   Accengage                           0x00000001039dcc68 A4SLog + 521
> 10  Accengage                           0x00000001039eb99a -[ACCPush resetBadge] + 23
> 11  Accengage                           0x00000001039ee907 __61-[ACCPush updateAuthorizedNotificationOptionsWithBadgeReset:]_block_invoke + 240
> 12  libdispatch.dylib                   0x0000000109624807 _dispatch_call_block_and_release + 12
> 13  libdispatch.dylib                   0x0000000109625848 _dispatch_client_callout + 8
> 14  libdispatch.dylib                   0x000000010962dc41 _dispatch_queue_serial_drain + 1305
> 15  libdispatch.dylib                   0x000000010962e556 _dispatch_queue_invoke + 328
> 16  libdispatch.dylib                   0x000000010962a3a0 _dispatch_queue_override_invoke + 726
> 17  libdispatch.dylib                   0x00000001096313c8 _dispatch_root_queue_drain + 664
> 18  libdispatch.dylib                   0x00000001096310d2 _dispatch_worker_thread3 + 132
> 19  libsystem_pthread.dylib             0x0000000109beb169 _pthread_wqthread + 1387
> 20  libsystem_pthread.dylib             0x0000000109beabe9 start_wqthread + 13
> -canOpenURL: failed for URL: "bma4sreceiver://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

**Comment by oristanovic** [comment]
Could you please provide your version info (SDK and iOS) ?

**Comment by ghost** [comment]
it is 6.1.1 version of SDK and tested on 11.3

**Comment by oristanovic** [comment]
These warnings were fixed starting from version 6.1.2. Feel free to reopen the issue if you encounter the same problem after updating to the latest SDK version.

**Comment by ghost** [comment]
It works, thanks
