### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Igor-Palaguta** [Accengage/accengage-ios-sdk-releases#2]
Hello,

Currently there is no way to use Accengage with Carthage.

Can you please add version file for Carthage for binary only frameworks:

e.g. accengage-ios-sdk-releases.json
```json
{
  "6.3.0": "https://github.com/Accengage/accengage-ios-sdk-releases/releases/download/6.3.0/Accengage.framework.zip"
}
```

accengage-ios-extension-sdk-releases.json
```json
{
  "1.1.0": "https://github.com/Accengage/accengage-ios-extension-sdk-releases/releases/download/1.1.0/AccengageExtension.framework.zip"
}
```

I can create PR if you agree

**Comment by oristanovic** [comment]
Hi, 
Sure, I see no problem with that.
