### ISSUE TITLE
no shared framework scheme for platform iOS

### ISSUE THREAD

**Issue by tonnihyldgaard** [Accengage/accengage-ios-sdk-releases#4]
Received this when I did a bootstrap to build for iOS only with Carthage: 

Dependency "accengage-ios-extension-sdk-releases" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Accengage/accengage-ios-extension-sdk-releases/issues/new
*** Skipped building accengage-ios-sdk-releases due to the error:
Dependency "accengage-ios-sdk-releases" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Accengage/accengage-ios-sdk-releases/issues/new

**Comment by oristanovic** [comment]
Could you share the contents of your cartfile and the xcodebuild log ?
Do you get the same message when you run carthage update ?

**Comment by oristanovic** [comment]
I'll close this for now. Feel free to reopen if necessary
