### ISSUE TITLE
Accengage.profile can be nil

### ISSUE THREAD

**Issue by Igor-Palaguta** [Accengage/accengage-ios-sdk-releases#5]
`profile` is expected to be not nullable as it is declared in NONNULL section, but really after launch it can be nil

`NS_ASSUME_NONNULL_BEGIN`

`+ (ACCUserProfile *)profile;`

`NS_ASSUME_NONNULL_END`

Accengage version 6.4.1

**Comment by Igor-Palaguta** [comment]
Same behaviour in 6.4.4

**Comment by Igor-Palaguta** [comment]
<img width="736" alt="Screenshot 2019-08-21 at 13 27 51" src="https://user-images.githubusercontent.com/800044/63428299-8a97b200-c417-11e9-8fed-a72a29e77fc0.png">

**Comment by oristanovic** [comment]
You need to start the SDK before calling any other methods. We'll update the ACCUserProfile annotation in the next release for clarity sake.

**Comment by Igor-Palaguta** [comment]
@oristanovic Thank you for response. I think I checked it also immediately after initializing SDK and had same effect. Will double check it

**Comment by Igor-Palaguta** [comment]
<img width="585" alt="Screenshot 2019-08-29 at 12 38 47" src="https://user-images.githubusercontent.com/800044/63933667-01f1c500-ca5a-11e9-8b70-8f877efb2bc0.png">

**Comment by oristanovic** [comment]
fixed in 7.0.0

**Comment by Igor-Palaguta** [comment]
@oristanovic thank you!

**Comment by Igor-Palaguta** [comment]
Looks like binary does not contain architecture for simulator

<img width="703" alt="Screenshot 2019-09-18 at 10 50 35" src="https://user-images.githubusercontent.com/800044/65133100-61604680-da02-11e9-8624-081584c8e875.png">

**Comment by oristanovic** [comment]
Thanks for letting us know. The build has been updated, could you check if it's working fine on your side now please ?

**Comment by Igor-Palaguta** [comment]
@oristanovic unfortunately same issue when using Carthage

**Comment by oristanovic** [comment]
Could you run lipo -info on the Accengage.framework you're using? What version of Xcode are you on?

**Comment by Igor-Palaguta** [comment]
```shell
Accengage.framework $lipo -info Accengage 
Non-fat file: Accengage is architecture: arm64
```

**Comment by Igor-Palaguta** [comment]
It also can be issue with Carthage Cache. Let me manual download zip

**Comment by Igor-Palaguta** [comment]
In zip everything is fine
```
Accengage.framework $lipo -info Accengage
Architectures in the fat file: Accengage are: x86_64 arm64 
```

Checking Carthage Cache. Version remained the same 7.0.0, so probably it did not update anything

**Comment by Igor-Palaguta** [comment]
Removing cache helped:
`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

**Comment by Igor-Palaguta** [comment]
During archiving with Xcode 10 we have following issue:

```
23:18:54 error: exportArchive: Failed to verify bitcode in Accengage.framework/Accengage:
23:18:54 error: Linker option verification failed for bundle /var/folders/c7/sdbxjwrn7l98nk8yks9dgbfr0000f5/T/AccengagegHAa0G/Accengage.arm64.xar (unrecognized arguments: -platform_version iOS 11.0.0 13.0.0)
```

Does it mean new version is just for Xcode 11

**Comment by oristanovic** [comment]
Yes, Xcode 11 is required for the SDK 7.0.0
